
all: rules-all

#fig12.4-detach:
#	$(IGNORE)

fig12.8-timeout: fig12.4-detach.o fig12.8-timeout.o
	$(BUILD)

fig12.11-getenv1.o:
	$(IGNORE)

#fig12.11-getenv1:
#	$(IGNORE)
#
#fig12.12-getenv2:
#	$(IGNORE)

fig12.13-getenv3.o:
	$(IGNORE)

#fig12.13-getenv3:
#	$(IGNORE)

include ../Make.rules
