
all: rules-all

#fig14.5-lockreg:
#	$(IGNORE)
#
#fig14.6-locktest:
#	$(IGNORE)
#
#fig14.9-lockfile:
#	$(IGNORE)
#
#fig14.16-isastream:
#	$(IGNORE)
#
#fig14.29a-readn:
#	$(IGNORE)
#
#fig14.29b-writen:
#	$(IGNORE)
#
include ../Make.rules
