
all: rules-all

#fig16.9-clconn:
#	$(IGNORE)
#
#fig16.10-initsrv1:
#	$(IGNORE)

fig16.14-ruptime: fig16.9-clconn.o fig16.10-initsrv1.o fig16.14-ruptime.o
	$(BUILD)

fig16.15-ruptimed: fig16.10-initsrv1.o fig16.15-ruptimed.o
	$(BUILD)

fig16.16-ruptimed-fd: fig16.10-initsrv1.o fig16.16-ruptimed-fd.o
	$(BUILD)

fig16.17-ruptimed-dg: fig16.10-initsrv1.o fig16.17-ruptimed-dg.o
	$(BUILD)

#fig16.20-initsrv2:
#	$(IGNORE)

include ../Make.rules
