
all: rules-all

#fig13.1-init:
#	$(IGNORE)
#
#fig13.6-single:
#	$(IGNORE)

fig13.7-reread: fig13.6-single.o fig13.7-reread.o ../ch14/fig14.9-lockfile.o
	$(BUILD)

fig13.8-reread2: fig13.6-single.o fig13.8-reread2.o ../ch14/fig14.9-lockfile.o
	$(BUILD)

include ../Make.rules
