
all: rules-all

fig17.27-main:	fig17.27-main.o fig17.28-open.o
	$(BUILD)

fig17.30-main:	fig17.30-main.o fig17.31-request.o fig17.33-cliargs.o
	$(BUILD)

fig17.37-main:	fig17.33-cliargs.o fig17.37-main.o fig17.36-client.o \
		fig17.38-loop.select.o fig17.40-request.o
	$(BUILD)

include ../Make.rules
