
all: rules-all

#fig10.7-sleep1:
#	$(IGNORE)
#	
#fig10.8-sleep2:
#	$(IGNORE)
#
fig10.9-tsleep2: fig10.8-sleep2.o fig10.9-tsleep2.o
	$(BUILD)

fig10.12-setops.o:
	$(IGNORE)

#fig10.12-setops:
#	$(IGNORE)
#
#fig10.14-prmask:
#	$(IGNORE)
#
#fig10.18-signal:
#	$(IGNORE)
#
#fig10.19-signalintr:
#	$(IGNORE)
#
#fig10.24-tellwait:
#	$(IGNORE)
#
#fig10.25-abort:
#	$(IGNORE)
#
#fig10.28-system:
#	$(IGNORE)
#
#fig10.29-sleep:
#	$(IGNORE)

include ../Make.rules
